c_compiler:
  - vs2022                     # [win]
  - clang                      # [linux]
c_compiler_version:
  - 17                         # [linux]
cxx_compiler:
  - vs2022                     # [win]
  - clangxx                    # [linux]
cxx_compiler_version:
  - 17                         # [linux]
