{% set name = 'libdispatch' %}
{% set version = '5.10.1' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apple/swift-corelibs-libdispatch/archive/refs/tags/swift-{{ version }}-RELEASE.tar.gz
  sha256: affa3544b0fdb60f8f175bc0d2846177436d5848ef8ca73e3e560d23986f38b3
  patches:
    - 0001-glibc-unistd-wrapper.patch  # [linux]

build:
  number: 0
  skip: true  # [osx]
  run_exports:
    - {{ pin_subpackage(name) }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - lld  # [win]
    - sysroot_linux-64 2.17  # [linux64]
    - cmake
    - ninja

test:
  commands:
    - test -f $PREFIX/lib/libdispatch${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\dispatch.lib exit 1  # [win]

about:
  home: https://github.com/apple/swift-corelibs-libdispatch
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Comprehensive support for concurrent code execution on multicore hardware'
  description: 'The libdispatch Project, (a.k.a. Grand Central Dispatch), for concurrency on multicore hardware'
  doc_url: https://apple.github.io/swift-corelibs-libdispatch
  dev_url: https://github.com/apple/swift-corelibs-libdispatch

extra:
  recipe-maintainers:
    - chawyehsu
